### ISSUE TITLE
Conflict with EDD

### ISSUE THREAD

**Issue by dovy** [microsoft/bing-wordpress-url-submission-plugin#4]
When trying to update a file I get this error in Easy Digital Downloads. You need to try/catch this so you don't break websites.

```Fatal error: Uncaught Error: Can only throw objects in /www/redux_896/public/wp-content/plugins/bing-webmaster-tools/admin/utils/class-bing-url-submission-admin-routes.php:303 Stack trace: #0 /www/redux_896/public/wp-content/plugins/bing-webmaster-tools/admin/class-bing-url-submission-admin.php(178): Bing_Webmaster_Admin_Routes->submit_url_to_bwt('https://redux.i...', 'https://redux.i...', '0565c0ea6ba8421...', 'update', false) #1 /www/redux_896/public/wp-includes/class-wp-hook.php(287): Bing_Webmaster_Admin->on_post_published('publish', 'publish', Object(WP_Post)) #2 /www/redux_896/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #3 /www/redux_896/public/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #4 /www/redux_896/public/wp-includes/post.php(4667): do_action('transition_post...', 'publish', 'publish', Object(WP_Post)) #5 /www/redux_896/public/wp-includes/post.php(4054): wp_transition_post_status('publish', 'publish', Object(WP_Post)) #6 /www/redux_896/public/wp-includes/post.php( in /www/redux_896/public/wp-content/plugins/bing-webmaster-tools/admin/utils/class-bing-url-submission-admin-routes.php on line 303```

**Comment by J-Rey** [comment]
I've got the same error a few different times after going over the daily quota. Have you noticed any failed submissions as well?

**Comment by dovy** [comment]
Not sure yet. Also found some react bugs in the console...
